language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore
  - dotnet build
addons:
    apt:
        packages:
            - sshpass
deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy.sh